[Icon Theme]
Name=phlat
Comment=The phlat icon theme
Example=face-wink
Inherits=hicolor

Directories=symbolic,symbolic-22,symbolic-24,symbolic-32,symbolic-48,emblems,emblems-24

[symbolic]
Size=16
Context=Actions
Type=Scalable

[symbolic]
Size=16
Context=Applications
Type=Scalable

[symbolic]
Size=16
Context=MimeTypes
Type=Scalable

[symbolic]
Size=16
Context=Devices
Type=Scalable

[symbolic]
Size=16
Context=Emotes
Type=Scalable

[symbolic]
Size=16
Context=FileSystems
Type=Scalable

[symbolic]
Size=16
Context=Places
Type=Scalable

[symbolic]
Size=16
Context=Categories
Type=Scalable

[symbolic]
Size=16
Context=Status
Type=Scalable

[symbolic]
Size=16
Context=Stock
Type=Scalable

[symbolic-22]
Size=22
Context=Actions
Type=Scalable

[symbolic-22]
Size=22
Context=Applications
Type=Scalable

[symbolic-22]
Size=22
Context=MimeTypes
Type=Scalable

[symbolic-22]
Size=22
Context=Devices
Type=Scalable

[symbolic-22]
Size=22
Context=Emotes
Type=Scalable

[symbolic-22]
Size=22
Context=FileSystems
Type=Scalable

[symbolic-22]
Size=22
Context=Places
Type=Scalable

[symbolic-22]
Size=22
Context=Categories
Type=Scalable

[symbolic-22]
Size=22
Context=Status
Type=Scalable

[symbolic-22]
Size=22
Context=Stock
Type=Scalable

[symbolic-24]
Size=24
Context=Actions
Type=Scalable

[symbolic-24]
Size=24
Context=Applications
Type=Scalable

[symbolic-24]
Size=24
Context=MimeTypes
Type=Scalable

[symbolic-24]
Size=24
Context=Devices
Type=Scalable

[symbolic-24]
Size=24
MaxSize=256
Context=Emotes
Type=Scalable

[symbolic-24]
Size=24
Context=FileSystems
Type=Scalable

[symbolic-24]
Size=24
Context=Places
Type=Scalable

[symbolic-24]
Size=24
Context=Categories
Type=Scalable

[symbolic-24]
Size=24
Context=Status
Type=Scalable

[symbolic-24]
Size=24
Context=Stock
Type=Scalable

[symbolic-32]
Size=16
MinSize=30
MaxSize=34
Context=Actions
Type=Scalable

[symbolic-32]
Size=16
MinSize=30
MaxSize=34
Context=Applications
Type=Scalable

[symbolic-32]
Size=16
MinSize=30
MaxSize=34
Context=MimeTypes
Type=Scalable

[symbolic-32]
Size=16
MinSize=30
MaxSize=34
Context=Devices
Type=Scalable

[symbolic-32]
Size=16
MinSize=30
MaxSize=34
MaxSize=256
Context=Emotes
Type=Scalable

[symbolic-32]
Size=16
MinSize=30
MaxSize=34
Context=FileSystems
Type=Scalable

[symbolic-32]
Size=16
MinSize=30
MaxSize=34
Context=Places
Type=Scalable

[symbolic-32]
Size=16
MinSize=30
MaxSize=34
Context=Categories
Type=Scalable

[symbolic-32]
Size=16
MinSize=30
MaxSize=34
Context=Status
Type=Scalable

[symbolic-32]
Size=16
MinSize=30
MaxSize=34
Context=Stock
Type=Scalable

[symbolic-48]
Size=24
MinSize=48
Context=Actions
Type=Scalable

[symbolic-48]
Size=24
MinSize=48
Context=Applications
Type=Scalable

[symbolic-48]
Size=24
MinSize=48
Context=MimeTypes
Type=Scalable

[symbolic-48]
Size=24
MinSize=48
Context=Devices
Type=Scalable

[symbolic-48]
Size=24
MinSize=48
Context=Emotes
Type=Scalable

[symbolic-48]
Size=24
MinSize=48
Context=FileSystems
Type=Scalable

[symbolic-48]
Size=24
MinSize=48
Context=Places
Type=Scalable

[symbolic-48]
Size=24
MinSize=48
Context=Categories
Type=Scalable

[symbolic-48]
Size=24
MinSize=48
Context=Status
Type=Scalable

[symbolic-48]
Size=24
MinSize=48
Context=Stock
Type=Scalable

##Emblems

[emblems]
Size=16
Context=Emblems
Type=Scalable

[emblems-24]
Size=24
Context=Emblems
Type=Scalable
