[Icon Theme]
Name=phlat
Comment=The phlat icon theme
Example=face-wink
Inherits=hicolor

Directories=symbolic,symbolic-22,symbolic-24,symbolic-32,emblems,emblems-24

[symbolic]
Size=16
Context=Actions
Type=Scalable

[symbolic]
Size=16
Context=Applications
Type=Scalable

[symbolic]
Size=16
Context=MimeTypes
Type=Scalable

[symbolic]
Size=16
Context=Devices
Type=Scalable

[symbolic]
Size=16
Context=Emotes
Type=Scalable

[symbolic]
Size=16
Context=FileSystems
Type=Scalable

[symbolic]
Size=16
Context=Places
Type=Scalable

[symbolic]
Size=16
Context=Categories
Type=Scalable

[symbolic]
Size=16
Context=Status
Type=Scalable

[symbolic]
Size=16
Context=Stock
Type=Scalable

[symbolic-22]
Size=22
Context=Actions
Type=Scalable

[symbolic-22]
Size=22
Context=Applications
Type=Scalable

[symbolic-22]
Size=22
Context=MimeTypes
Type=Scalable

[symbolic-22]
Size=22
Context=Devices
Type=Scalable

[symbolic-22]
Size=22
Context=Emotes
Type=Scalable

[symbolic-22]
Size=22
Context=FileSystems
Type=Scalable

[symbolic-22]
Size=22
Context=Places
Type=Scalable

[symbolic-22]
Size=22
Context=Categories
Type=Scalable

[symbolic-22]
Size=22
Context=Status
Type=Scalable

[symbolic-22]
Size=22
Context=Stock
Type=Scalable

[symbolic-24]
Size=24
Context=Actions
Type=Scalable

[symbolic-24]
Size=24
Context=Applications
Type=Scalable

[symbolic-24]
Size=24
Context=MimeTypes
Type=Scalable

[symbolic-24]
Size=24
Context=Devices
Type=Scalable

[symbolic-24]
Size=24
MaxSize=256
Context=Emotes
Type=Scalable

[symbolic-24]
Size=24
Context=FileSystems
Type=Scalable

[symbolic-24]
Size=24
Context=Places
Type=Scalable

[symbolic-24]
Size=24
Context=Categories
Type=Scalable

[symbolic-24]
Size=24
Context=Status
Type=Scalable

[symbolic-24]
Size=24
Context=Stock
Type=Scalable

###unblur the 32px icons

[symbolic-32]
Size=16
MaxSize=33
MinSize=31
Context=Actions
Type=Scalable

[symbolic-32]
Size=16
MaxSize=33
MinSize=31
Context=Applications
Type=Scalable

[symbolic-32]
Size=16
MaxSize=33
MinSize=31
Context=MimeTypes
Type=Scalable

[symbolic-32]
Size=16
MaxSize=33
MinSize=31
Context=Devices
Type=Scalable

[symbolic-32]
Size=16
MaxSize=33
MinSize=31
MaxSize=256
Context=Emotes
Type=Scalable

[symbolic-32]
Size=16
MaxSize=33
MinSize=31
Context=FileSystems
Type=Scalable

[symbolic-32]
Size=16
MaxSize=33
MinSize=31
Context=Places
Type=Scalable

[symbolic-32]
Size=16
MaxSize=33
MinSize=31
Context=Categories
Type=Scalable

[symbolic-32]
Size=16
MaxSize=33
MinSize=31
Context=Status
Type=Scalable

[symbolic-32]
Size=16
MaxSize=33
MinSize=31
Context=Stock
Type=Scalable

##Emblems

[emblems]
Size=16
Context=Emblems
Type=Scalable

[emblems-24]
Size=24
Context=Emblems
Type=Scalable
