style"gtknotebook"{
xthickness=0
ythickness=0
GtkNotebook::tab-curvature=10
GtkNotebook::tab-overlap=1
GtkNotebook::has-backward-stepper=0
GtkNotebook::has-forward-stepper=1
GtkNotebook::has-secondary-backward-stepper=1
GtkNotebook::has-secondary-forward-stepper=0
engine"pixmap"{
image{
function=SHADOW
file="../images/gtk-2.0/none.svg"
stretch=FALSE}
image{
function=BOX_GAP
file="../images/gtk-2.0/arrow-bg.svg"
detail="notebook"
border={4,4,4,4}
stretch=TRUE}
image{
function=EXTENSION
state=ACTIVE
file="../images/gtk-2.0/tab_normal.svg"
border={1,1,1,1}
stretch=TRUE}
image{
function=EXTENSION
file="../images/gtk-2.0/tab_active.svg"
border={1,1,1,1}
stretch=TRUE
}}}class"GtkNotebook"style"gtknotebook"

style"gtknotebook2"{
bg[NORMAL]=@base_color
bg[PRELIGHT]=@base_color
bg[SELECTED]=@base_color
bg[ACTIVE]=@base_color
bg[INSENSITIVE]=@base_color
engine"pixmap"{
image{
function=BOX
state=INSENSITIVE
shadow=OUT
file="../images/gtk-2.0/tab_normal.svg"
border={1,1,1,1}
stretch=TRUE}
image{
function=BOX
state=NORMAL
shadow=OUT
file="../images/gtk-2.0/tab_normal.svg"
border={1,1,1,1}
stretch=TRUE}
image{
function=BOX
state=PRELIGHT
shadow=OUT
file="../images/gtk-2.0/tab_normal.svg"
border={1,1,1,1}
stretch=TRUE}
image{
function=BOX
state=SELECTED
shadow=OUT
file="../images/gtk-2.0/tab_normal.svg"
border={1,1,1,1}
stretch=TRUE}
image{
function=BOX
state=ACTIVE
shadow=OUT
file="../images/gtk-2.0/tab_normal.svg"
border={1,1,1,1}
stretch=TRUE}
image{
function=BOX
state=INSENSITIVE
shadow=IN
file="../images/gtk-2.0/tab_normal.svg"
border={1,1,1,1}
stretch=TRUE}
image{
function=BOX
state=NORMAL
shadow=IN
file="../images/gtk-2.0/tab_normal.svg"
border={1,1,1,1}
stretch=TRUE}
image{
function=BOX
state=PRELIGHT
shadow=IN
file="../images/gtk-2.0/tab_active.svg"
border={1,1,1,1}
stretch=TRUE}
image{
function=BOX
state=SELECTED
shadow=IN
file="../images/gtk-2.0/tab_active.svg"
border={1,1,1,1}
stretch=TRUE}
image{
function=BOX
state=ACTIVE
shadow=IN
file="../images/gtk-2.0/tab_active.svg"
border={1,1,1,1}
stretch=TRUE}
image{
detail="buttondefault"
file="../images/gtk-2.0/none.svg"
stretch=FALSE}
image{
detail="focus"
file="../images/gtk-2.0/none.svg"
stretch=FALSE}}}
widget_class"*GtkNotebook*GtkButton*"style"gtknotebook2"
